name: My check

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Start PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '16'
          postgresql db: task_manager_vhv3
          postgresql user: task_manager_vhv3_user
          postgresql password: ${{ secrets.DB_PASSWORD }}

      - name: Install project
        run: make install

      - name: Set up environment
        run: |
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=task_manager_vhv3" >> .env
          echo "DB_USERNAME=task_manager_vhv3_user" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Run linter
        run: make lint

      - name: Download Code Climate Test Reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter

      - name: Give execute permissions
        run: chmod +x cc-test-reporter

      - name: Before running tests (initialize Code Climate)
        run: ./cc-test-reporter before-build

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          XDEBUG_MODE=coverage composer exec phpunit tests -- --coverage-clover=coverage/clover.xml

      - name: Upload coverage to Code Climate
        run: |
          ./cc-test-reporter format-coverage -t clover coverage/clover.xml
          ./cc-test-reporter upload-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-coverage
          path: coverage/clover.xml